name: LunarRaid
favicon: null
layout_spectrum: 0.2616
typography_spectrum: 0.6528844833374023
title: LunarRaid.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8e8e8'
    - '#bebebe'
    - '#747474'
    - '#004000'
  brandStrength: 0.10344280069693923
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
